# frozen_string_literal: true

module A2A
  # Represents a file, data structure, or other resource generated by an agent during a task.
  class Artifact < ProtocolStruct
    # @return [String] A unique identifier (e.g. UUID) for the artifact within the scope of the task.
    attribute :artifact_id, Types::String

    # @return [String, nil] An optional, human-readable name for the artifact.
    attribute? :name, Types::String.optional

    # @return [String, nil] An optional, human-readable description of the artifact.
    attribute? :description, Types::String.optional

    # @return [Array<Part>] An array of content parts that make up the artifact.
    attribute :parts, Types::Array.of(Types::Constructor(Part))

    # @return [Hash, nil] Optional metadata for extensions. The key is an extension-specific identifier.
    attribute? :metadata, Types::Hash.optional

    # @return [Array<String>, nil] The URIs of extensions that are relevant to this artifact.
    attribute? :extensions, Types::Array.of(Types::String).optional
  end
end
